# global:
#   domain: argocd.example.com

configs:
  params:
    server.insecure: true

  # cm:
  #   url: https://argocd.example.com

  rbac:
    policy.default: role:readonly

server:
  replicas: 2

  service:
    type: ClusterIP

  # ingress:
  #   enabled: true
  #   ingressClassName: nginx
  #   hosts:
  #     - argocd.example.com
  #   paths:
  #     - /
  #   pathType: Prefix

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

repoServer:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

applicationSet:
  enabled: true

dex:
  enabled: false

redis:
  enabled: true

controller:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

